"""Idempotent demand initialization for the OSM-imported network
(Basler Str. × Obere Riehenstraße, Lörrach-Stetten, real geometry).

Unlike ``init_data_real.py`` (a hand-built schematic 4-arm intersection),
this module uses ``randomTrips.py`` on the OSM-derived ``loerrach_osm.net.xml``
because the network has many edges, on-ramps, and side streets - too many
to enumerate as OD pairs by hand.

The trip *count* is calibrated to the same BASt 2023 peak-hour magnitude as
``init_data_real.py`` (~680 veh/h at hour 16:00, Zst 8570). The departure
*period* is empirically tuned to ~2.9 s so that the post-validation trip
count after duarouter drops disconnected routes hits the target.

Run after the OSM network has been built:
    netconvert --osm-files data/raw/osm/loerrach_real_osm.osm.xml ...

Usage:
    python scripts/init_data_osm.py            # only missing files
    python scripts/init_data_osm.py --force    # regenerate all
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _resolve_sumo_home() -> Path:
    """Resolve SUMO_HOME OS-agnostically: env var first, else the pip ``sumo`` package.

    Mirrors ``run.py:bootstrap_sumo`` so this script works on macOS/Windows/Linux
    from a pip-only SUMO install - no hardcoded ``/usr/share/sumo``.
    """
    sumo_home = os.environ.get("SUMO_HOME")
    if not sumo_home:
        try:
            import sumo  # eclipse-sumo pip package exposes SUMO_HOME

            sumo_home = sumo.SUMO_HOME
        except Exception as exc:  # noqa: BLE001
            msg = ("SUMO_HOME is not set and the 'sumo' pip package is unavailable. "
                   "Run `pip install -r requirements.txt` or set SUMO_HOME manually.")
            raise FileNotFoundError(msg) from exc
    return Path(sumo_home)


NET_FILE = PROJECT_ROOT / "data" / "sumo_config" / "loerrach_osm.net.xml"
OUTPUT_DIR = PROJECT_ROOT / "data" / "sumo_config"
EPISODE_S = 3600

# Calibrated to hit BASt 2023 Zst 8570 peak-hour magnitude (~680 veh/h)
# after duarouter validation drops disconnected/illegal routes.
# Empirically: period 2.9 → 682 valid trips at fringe-factor 5, seed 42.
SCENARIOS: dict[str, float] = {
    "low": 4.83,     # ~410 valid trips/h  (≈ 60 % of medium)
    "medium": 2.9,   # ~680 valid trips/h  (BASt peak target)
    "high": 2.15,    # ~920 valid trips/h  (≈ 135 % of medium)
}
SEED = 42  # randomTrips seed; episode seeds are separate (RL eval)


def _have_randomtrips(sumo_home: Path) -> Path:
    rt = sumo_home / "tools" / "randomTrips.py"
    if not rt.exists():
        msg = f"randomTrips.py not found at {rt} (check SUMO_HOME)."
        raise FileNotFoundError(msg)
    return rt


def generate(scenario: str, period: float, force: bool) -> None:
    out_rou = OUTPUT_DIR / f"loerrach_osm_{scenario}.rou.xml"
    out_trips = OUTPUT_DIR / f"loerrach_osm_{scenario}.trips.xml"
    if out_rou.exists() and not force:
        print(f"[skip]   {out_rou.name} (exists; use --force)")
        return

    sumo_home = _resolve_sumo_home()
    rt = _have_randomtrips(sumo_home)
    cmd = [
        sys.executable, str(rt),
        "--net-file", str(NET_FILE),
        "--output-trip-file", str(out_trips),
        "--route-file", str(out_rou),
        "--period", str(period),
        "--end", str(EPISODE_S),
        "--prefix", "veh",
        "--vehicle-class", "passenger",
        "--validate",
        "--seed", str(SEED),
        "--fringe-factor", "5",
    ]
    env = dict(os.environ)
    env["SUMO_HOME"] = str(sumo_home)
    env["PATH"] = os.pathsep.join(p for p in (str(sumo_home / "bin"), env.get("PATH", "")) if p)
    subprocess.run(cmd, check=True, env=env, capture_output=True)
    n_trips = _count_vehicles(out_rou)
    print(f"[write]  {out_rou.name} ({n_trips} valid trips, period {period}s)")

    # Inject calibration provenance into the route-file comment header.
    _annotate(out_rou, scenario, period, n_trips)


def _count_vehicles(rou: Path) -> int:
    n = 0
    with rou.open() as fh:
        for line in fh:
            if "<vehicle " in line or "<trip " in line:
                n += 1
    return n


def _annotate(rou: Path, scenario: str, period: float, n_trips: int) -> None:
    """Replace the first XML-comment block with our provenance header."""
    text = rou.read_text()
    head, _, tail = text.partition("<routes")
    new_head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- Generated by scripts/init_data_osm.py - OSM-imported network\n"
        f"     Basler Str. × Obere Riehenstr., Lörrach-Stetten.\n"
        f"     Scenario: {scenario} ({n_trips} trips over {EPISODE_S}s,\n"
        f"     randomTrips.py period={period}s, validate, fringe-factor 5).\n"
        f"     Calibration target: BASt 2023 Zst 8570 peak-hour ≈ 680 veh/h\n"
        f"     (16:00 share = 8.46 % × DTV 8037 Kfz/24h).\n"
        f"     TLS under control: OSM ID 1628110071. -->\n"
    )
    rou.write_text(new_head + "<routes" + tail)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true",
                        help="Regenerate even if files exist")
    args = parser.parse_args()

    if not NET_FILE.exists():
        msg = f"Network file missing: {NET_FILE}"
        raise FileNotFoundError(msg)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for scenario, period in SCENARIOS.items():
        generate(scenario, period, args.force)


if __name__ == "__main__":
    main()
